version: "3.9"

x-frontend:
  &frontend
  container_name: diverse-frontend-$PROFILE
  pull_policy: always
  restart: unless-stopped
  build:
    context: .
    dockerfile: deploy/Dockerfile
    target: $PROFILE
    args:
      - BASE_HOST
      - VITE_APP_API_BASE_URL
  networks: [ frontend ]

services:
  frontend:
    <<: *frontend
    image: ghcr.io/mangrimen/diverse-front:latest
    profiles: [ prod ]
    ports: [ $FRONTEND_PORT_PROD:80 ]

  frontend-test:
    <<: *frontend
    image: ghcr.io/mangrimen/diverse-front:develop
    profiles: [ test ]
    ports: [ $FRONTEND_PORT_TEST:80 ]

networks:
  frontend:
    name: diverse-frontend-${PROFILE}
